Traceback (most recent call last):
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import math
# Conseils : S'il vous plaÃ®t, n'enlevez pas le \n que votre TA a soigneusement mis dans le code !
with open(________, '_', encoding="utf-8") as fhandler:
  fhandler.write('______________________\n')

with open(________, '__', encoding="utf-8") as fhandler:
  print(fhandler.readlines())
  # Votre TA souhaite une prÃ©cision Ã  la quatriÃ¨me dÃ©cimale ici.
  firstline = f'____________________________ {math.pi:._f}\n'
  secondline = '_____________________________\n'
  thirdline = '___________________________\n'
  fhandler.writelines([___,____,___])
  # Aller au dÃ©but du fichier
  fhandler.seek(0)
  # Imprimer le contenu du fichier
  print(fhandler.readlines())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmath[39;00m
[1;32m      2[0m [38;5;66;03m# Conseils : S'il vous plaÃ®t, n'enlevez pas le \n que votre TA a soigneusement mis dans le code ![39;00m
[0;32m----> 3[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m([43m________[49m, [38;5;124m'[39m[38;5;124m_[39m[38;5;124m'[39m, encoding[38;5;241m=[39m[38;5;124m"[39m[38;5;124mutf-8[39m[38;5;124m"[39m) [38;5;28;01mas[39;00m fhandler:
[1;32m      4[0m   fhandler[38;5;241m.[39mwrite([38;5;124m'[39m[38;5;124m______________________[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m)
[1;32m      6[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m(________, [38;5;124m'[39m[38;5;124m__[39m[38;5;124m'[39m, encoding[38;5;241m=[39m[38;5;124m"[39m[38;5;124mutf-8[39m[38;5;124m"[39m) [38;5;28;01mas[39;00m fhandler:

[0;31mNameError[0m: name '________' is not defined

